### ISSUE TITLE
Weird encoding for several poems

### ISSUE THREAD

**Issue by kimt33** [chalmerlowe/intro_to_sprinting_codeless_project#134]
The following files have characters that are not supported by utf-8:
`beowulf.txt`
`the_raven.txt`
`the_road_not_taken.txt`

The last two can be fixed by hand, but beowulf is quite long and will need some sort of script. I'm not too sure how to do use regex for non-unicode character.

**Comment by rora002** [comment]
I have just created an alternative pull request, which updates fewer lines of beowolf.txt

**Comment by seawolf42** [comment]
fixed by #136
